### ISSUE TITLE
oma_protein-

### ISSUE THREAD

**Issue by yatsuzuka-nbdc** [togoid/togoid-config#34]

**Comment by hchiba1** [comment]
修正完了しました.

**Comment by hchiba1** [comment]
oma_protein 系は
```
?oma_protein orth:organism/obo:RO_0002162 uptax:9606 .
```
ヒトしか取っていないようだけどよい？

**Comment by hchiba1** [comment]
オリジナルのTSVファイル ( https://omabrowser.org/All/oma-uniprot.txt.gz ) もあるが、
SPARQLで取得した結果と比べると微妙に異なっているようだ.
TSVの方には、UniProtニーモニックが混じっているという問題がありそうである.
またSPARQLの場合、ウェブサイトではOMAからUniProtに直接つながっていなかったものにもリンクを張っているように見える.

SPARQLの方を採用することにする.
Taxonomy IDごとにクエリをかけて回すため、時間がかかる (約2500生物, 70分ほど).
